In [ ]:
import datetime
from argparse import ArgumentParser
from pathlib import Path
import h5py
import numpy as np
import pandas as pd
from pynwb import NWBHDF5IO
from sklearn.model_selection import train_test_split


from torch_brain.data import (
    BrainsetDescription,
    Data,
    DeviceDescription,
    Interval,
    RegularTimeSeries,
    SessionDescription,
    serialize_fn_map,
)
from torch_brain.pipeline import BrainsetPipeline
from torch_brain.utils.dandi import (
    download_file,
    extract_spikes_from_nwbfile,
    extract_subject_from_nwb,
    get_nwb_asset_list,
)

brainset_id = "nlb_area2_2021"
fpath = r"C:\Workspace\SSM-BCI-Repo\data\raw\nlb_area2_2021\sub-Han_desc-train_behavior+ecephys.nwb"
processed_dir = Path(r"C:\Workspace\SSM-BCI-Repo\data\processed\nlb_area2_2021")

ModuleNotFoundError: No module named 'sklearn'

In [93]:
import numpy as np

def split_trials(trials, test_size=0.2, valid_size=0.1):
    num_trials = len(trials)
    
    # Calculate the exact splitting index boundaries
    train_end = int(num_trials * (1.0 - test_size - valid_size))
    valid_end = int(num_trials * (1.0 - test_size))
    
    # Create the sequential index arrays
    train_ids = np.arange(0, train_end)
    valid_ids = np.arange(train_end, valid_end)
    test_ids = np.arange(valid_end, num_trials)
    
    # Select the trials using your mask method
    train_trials = trials.select_by_mask(np.isin(np.arange(num_trials), train_ids))
    valid_trials = trials.select_by_mask(np.isin(np.arange(num_trials), valid_ids))
    test_trials = trials.select_by_mask(np.isin(np.arange(num_trials), test_ids))
    
    return train_trials, valid_trials, test_trials

def extract_behavior(nwbfile):
    """Extract behavior from the NWB file.

    ..note::
        - Only care about hand velocity
        - Timestamps not present in the NWB file
    """
    # cursor, hand and eye share the same timestamps (verified)
    raw_hand_vel = nwbfile.processing["behavior"]["hand_vel"].data[:]

    # These samples are uniformly sampled at 1000Hz,
    samp_rate = 1e3
    num_timesteps = raw_hand_vel.shape[0]
    start_time = 0.0

    hand = RegularTimeSeries(
        sampling_rate=samp_rate,
        # pos=hand_pos,
        vel=raw_hand_vel,
        domain="auto",
        domain_start=start_time,
    )
    
    return hand



def extract_center_out_reaching_trials(nwbfile, hand):
    r"""Extract trial information from the NWB file. Trials that are flagged as
    "to discard" or where the monkey failed are marked as invalid."""
    trial_table = nwbfile.trials.to_dataframe()

    # infer the trial structure from the trial table
    trial_grid = np.append(
        trial_table.target_on_time.iloc[:],
        min(trial_table.stop_time.iloc[-1] + 1.0, hand.domain.end[-1]),
    )

    default_value = np.append(
        trial_table.start_time.iloc[0], trial_table.stop_time.values + 1.0
    )
    default_value[1:-1] = np.minimum(
        default_value[1:-1], trial_table.stop_time.values[1:]
    )
    nan_mask = np.isnan(trial_grid)
    trial_grid[nan_mask] = default_value[nan_mask]
    trial_grid = trial_grid.astype(np.float64)
    trial_table["end"] = trial_grid[1:]
    trial_table["start"] = trial_grid[:-1]

    trial_table = trial_table.rename(
        columns={
            "split": "split_indicator",
        }
    )

    trials = Interval.from_dataframe(trial_table)
    assert trials.is_disjoint()

    # find valid trials
    success_mask = trials.result == "R"
    # valid_target_mask = ~np.isnan(trials.target_id)
    max_duration_mask = (trials.end - trials.start) < 6.0
    min_duration_mask = (trials.end - trials.start) > 0.5

    trials.is_valid = (
        success_mask & max_duration_mask & min_duration_mask
        # success_mask & valid_target_mask & max_duration_mask & min_duration_mask
    )

    valid_trials = trials.select_by_mask(trials.is_valid)

    # isolate movement phases
    movement_phases = Data(
        hold_period=Interval(
            start=valid_trials.target_on_time, end=valid_trials.go_cue_time
        ),
        reach_period=Interval(
            start=valid_trials.go_cue_time, end=valid_trials.stop_time
        ),
        return_period=Interval(start=valid_trials.stop_time, end=valid_trials.end),
        invalid=trials.select_by_mask(~trials.is_valid),
        domain="auto",
    )

    # everything outside of the different identified periods will be marked as random
    movement_phases.random_period = hand.domain.difference(movement_phases.domain)

    return trials, movement_phases


brainset_description = BrainsetDescription(
    id=brainset_id,
    origin_version="dandi/000127/0.220113.0359",
    derived_version="2.0.0",
    source="https://dandiarchive.org/dandiset/000127",
    description="This dataset contains sorted unit spiking times and behavioral data from " \
    "a macaque performing a reaching task with perturbations. In the experimental task, the " \
    "subject performed delayed center-out reaches using a manipulandum to control a cursor. " \
    "On a portion of the trials, the manipulandum applied a bump during the center hold prior " \
    "to the reach. Neural activity was recorded from an electrode array implanted in somatosensory " \
    "area 2. Hand position, cursor position, force applied to the manipulandum, length and velocity " \
    "of various arm muscles, and angle and velocity of various arm joints were all recorded during " \
    "the experiment. Provided as part of the Neural Latents Benchmark: https://neurallatents.github.io.",
)

# open file
io = NWBHDF5IO(fpath, "r")
nwbfile = io.read()
subject = extract_subject_from_nwb(nwbfile)

recording_date = nwbfile.session_start_time.strftime("%Y%m%d")
device_id = f"{subject.id}_{recording_date}"
session_id = f"{subject.id}_area2"
if "test" in str(fpath):
    session_id += "_test"
else:
    session_id += "_train"

store_path = processed_dir / f"{session_id}.h5"
if store_path.exists():
    assert f"{store_path} already exists. Do you want to overwrite it? (y/n)"

# register session
session_description = SessionDescription(
    id=session_id,
    recording_date=datetime.datetime.strptime(recording_date, "%Y%m%d"),
    task="REACHING",
)

# register device
device_description = DeviceDescription(
    id=device_id,
    recording_tech="UTAH_ARRAY_SPIKES",
)

# extract spiking activity
# this data is from dandi, we can use our helper function
spikes, units = extract_spikes_from_nwbfile(
    nwbfile,
    recording_tech="UTAH_ARRAY_SPIKES",
)

# extract behaviour
hand = extract_behavior(nwbfile)

# extract data about trial structure
# trials = extract_trials(nwbfile)
trials, movement_phases = extract_center_out_reaching_trials(
    nwbfile, 
    hand
)

data = Data(
    brainset=brainset_description,
    session=session_description,
    device=device_description,
    # neural activity
    spikes=spikes,
    units=units,
    # stimuli and behavior
    trials=trials,
    movement_phases=movement_phases,
    hand=hand,
    # domain
    domain=hand.domain,
)

if "test" not in str(fpath):
    print("-"*50)
    print("Creating splits...")
    _, valid_trials, test_trials = split_trials(
        trials.select_by_mask(trials.is_valid),
        test_size=0.2,
        valid_size=0.1
    )
    train_sampling_intervals = data.domain.difference(
        (valid_trials | test_trials).dilate(1.0)
    )

    data.train_domain = train_sampling_intervals
    data.valid_domain = valid_trials
    data.test_domain = test_trials

    io.close()

    print(train_sampling_intervals.start)
    print(train_sampling_intervals.end)
    print("-"*50)
    print(valid_trials.start)
    print(valid_trials.end)
    print("-"*50)
    print(test_trials.start)
    print(test_trials.end)

# # save data to disk
# with h5py.File(store_path, "w") as file:
#     data.to_hdf5(file, serialize_fn_map=serialize_fn_map)

--------------------------------------------------
Creating splits...
[   0.    1569.081 1574.503 1592.261 1598.479 1610.082 1631.39  1650.629
 1658.801 1680.478 1695.945 1707.412 1730.599 1744.223 1783.739 1797.356
 1812.774 1822.845 1830.461 1836.745 1855.629 1869.131 1879.422 1887.28
 1891.661 1917.75  1934.745 1943.623 1963.629 1972.385 1986.82  2014.493
 2024.636 2031.343 2037.453 2044.368 2063.923 2075.049 2083.881 2094.511
 2102.621 2119.779 2125.623 2130.227 2134.132 2153.442 2161.483 2192.472
 2198.252 2202.93  2220.495]
[1565.349 1570.937 1588.554 1594.799 1599.836 1610.876 1631.517 1650.847
 1662.947 1692.264 1703.411 1712.63  1738.49  1772.399 1791.289 1808.007
 1816.164 1823.778 1832.269 1846.81  1858.001 1873.118 1883.668 1888.087
 1892.748 1922.752 1937.786 1949.596 1965.014 1983.217 1996.024 2015.849
 2027.759 2033.841 2037.894 2049.826 2067.706 2075.146 2087.451 2098.677
 2108.42  2121.951 2126.544 2130.411 2147.871 2157.73  2176.832 2194.382
 2199.177 2205.191 2221.303]
--------------------------------------------------
[1566.349 1571.937 1589.554 1595.799 1600.836 1604.09  1607.687 1611.876
 1615.923 1621.723 1625.426 1628.663 1632.517 1636.463 1640.813 1644.238
 1648.032 1651.847 1656.18  1663.947 1666.74  1671.363 1675.018 1677.681
 1693.264 1704.411 1713.63  1717.553 1720.887 1723.931 1739.49  1773.399
 1777.27  1781.153 1792.289 1809.007]
[1568.081 1573.503 1591.261 1597.479 1604.09  1605.823 1609.082 1615.923
 1621.723 1625.426 1628.663 1630.39  1636.463 1640.813 1644.238 1648.032
 1649.629 1656.18  1657.801 1666.74  1671.363 1675.018 1677.681 1679.478
 1694.945 1706.412 1717.553 1720.887 1723.931 1729.599 1743.223 1777.27
 1781.153 1782.739 1796.356 1811.774]
--------------------------------------------------
[1817.164 1820.277 1824.778 1828.049 1833.269 1847.81  1851.729 1859.001
 1863.101 1866.412 1874.118 1876.737 1884.668 1889.087 1893.748 1896.538
 1902.004 1904.731 1908.169 1911.493 1914.254 1923.752 1927.169 1931.925
 1938.786 1950.596 1954.276 1957.944 1960.887 1966.014 1970.182 1984.217
 1997.024 2000.625 2004.635 2008.235 2011.821 2016.849 2021.739 2028.759
 2034.841 2038.894 2041.877 2050.826 2055.3   2058.286 2061.204 2068.706
 2072.427 2076.146 2079.075 2088.451 2091.966 2099.677 2109.42  2113.647
 2116.544 2122.951 2127.544 2131.411 2148.871 2158.73  2177.832 2181.151
 2184.744 2188.018 2195.382 2200.177 2206.191 2209.78  2213.402 2216.148
 2222.303]
[1820.277 1821.845 1828.049 1829.461 1835.745 1851.729 1854.629 1863.101
 1866.412 1868.131 1876.737 1878.422 1886.28  1890.661 1896.538 1902.004
 1904.731 1908.169 1909.575 1914.254 1916.75  1927.169 1931.925 1933.745
 1942.623 1954.276 1957.944 1960.887 1962.629 1970.182 1971.385 1985.82
 2000.625 2004.635 2008.235 2011.821 2013.493 2021.739 2023.636 2030.343
 2036.453 2041.877 2043.368 2055.3   2058.286 2061.204 2062.923 2072.427
 2074.049 2079.075 2082.881 2091.966 2093.511 2101.621 2113.647 2116.544
 2118.779 2124.623 2129.227 2133.132 2152.442 2160.483 2181.151 2184.744
 2188.018 2191.472 2197.252 2201.93  2209.78  2213.402 2216.148 2219.495
 2223.449]

C:\Users\Hsien Rong\AppData\Local\Temp\ipykernel_5276\3308950798.py:37: DeprecationWarning: The `domain` argument of `RegularTimeSeries` is deprecated and will be removed in a future version. The domain is always computed automatically as [domain_start, domain_start + len(self) / sampling_rate); you can drop `domain="auto"` from your call.
  hand = RegularTimeSeries(

In [27]:
spikes

IrregularTimeSeries(
  timestamps=[1017465],
  unit_index=[1017465]
)

In [51]:
# io = NWBHDF5IO(rf"C:\Workspace\SSM-BCI-Repo\data\raw\nlb_area2_2021\sub-Han_desc-test_ecephys.nwb", "r")
io = NWBHDF5IO(rf"C:\Workspace\SSM-BCI-Repo\data\raw\nlb_area2_2021\sub-Han_desc-train_behavior+ecephys.nwb", "r")

nwbfile = io.read()
nwbfile

root pynwb.file.NWBFile at 0x2321746550096
Fields:
  devices: {
    electrode_array <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    electrode_group <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'pynwb.ecephys.ElectrodesTable'>
  experiment_description: Center out reaching task with perturbations during center hold period before reach
  experimenter: ['Raeed H. Chowdhury']
  file_create_date: [datetime.datetime(2021, 9, 1, 21, 40, 32, 929476, tzinfo=tzoffset(None, -14400))]
  identifier: c32b334c-0b8e-11ec-b9b7-0bfeb2c344ea
  institution: Northwestern University
  intervals: {
    trials <class 'pynwb.epoch.TimeIntervals'>
  }
  keywords: <StrDataset for HDF5 dataset "keywords": shape (4,), type "|O">
  lab: Miller
  processing: {
    behavior <class 'pynwb.base.ProcessingModule'>
  }
  related_publications: ['https://doi.org/10.7554/eLife.48198']
  session_description: Data from monkey Han performing center-out active-passive task. This file contains several continuous segments of the full session on 2017-12-07 that can be used for training models for the Neural Latents Benchmark.
  session_id: 20171207
  session_start_time: 2017-12-07 17:06:09.727000-05:00
  subject: subject pynwb.file.Subject at 0x2321744615568
Fields:
  sex: M
  species: Macaca mulatta
  subject_id: Han

  timestamps_reference_time: 2017-12-07 17:06:09.727000-05:00
  trials: trials <class 'pynwb.epoch.TimeIntervals'>
  units: units <class 'pynwb.misc.Units'>

In [52]:
print(nwbfile.trials.to_dataframe().to_string())

     start_time  stop_time result  ctr_hold  ctr_hold_bump  bump_dir  target_on_time  target_dir  go_cue_time  bump_time  move_onset_time  cond_dir  split
id
0         0.502      4.556      R  1.106973          False       NaN           3.734        45.0        3.735        NaN            4.075      45.0    val
1         5.059      5.588      A  1.344188           True       NaN             NaN       225.0          NaN        NaN              NaN       NaN   none
2         6.090      9.374      I  1.170550           True     225.0           8.369       180.0        8.370      7.905            7.898     225.0   none
3         9.877     15.298      R  1.222202          False       NaN          14.318        45.0       14.319        NaN           14.656      45.0  train
4        15.800     17.005      A  0.777271          False       NaN             NaN       135.0          NaN        NaN              NaN     135.0   none
5        17.508     18.829      R  0.553678          False       NaN          18.245       270.0       18.246        NaN           18.508     270.0    val
6        19.331     22.551      R  1.424859          False       NaN          21.954       180.0       21.955        NaN           22.247     180.0  train
7        23.053     26.261      R  0.890691           True       0.0          25.656       135.0       25.657     25.062           25.062       0.0  train
8        26.764     28.601      A  0.573669           True       NaN             NaN       315.0          NaN        NaN              NaN       NaN   none
9        29.103     32.806      I  1.197885           True     135.0          31.801       225.0       31.802     31.265           31.280     135.0   none
10       33.308     35.997      R  0.590669           True     270.0          35.297         0.0       35.298     34.854           34.852     270.0    val
11       36.499     36.938      A  1.184729           True       NaN             NaN       270.0          NaN        NaN              NaN       NaN   none
12       37.440     37.687      A  1.431361           True       NaN          37.475        90.0          NaN        NaN              NaN       NaN   none
13       38.189     40.642      R  0.982830           True     135.0          39.847       315.0       39.848     39.357           39.371     135.0  train
14       41.144     42.004      A  1.045930           True       NaN             NaN       315.0          NaN        NaN              NaN       NaN   none
15       42.506     44.544      R  1.103750          False       NaN          43.795        45.0       43.796        NaN           44.107      45.0    val
16       45.046     45.451      A  1.260671          False       NaN             NaN         0.0          NaN        NaN              NaN       0.0   none
17       45.953     48.657      R  0.734950           True     225.0          47.935        45.0       47.936     46.764           46.757     225.0    val
18       49.159     51.658      R  1.095729          False       NaN          50.777       180.0       50.778        NaN           51.106     180.0  train
19       52.160     55.216      R  0.856059           True      90.0          54.580       180.0       54.581     54.094           54.088      90.0  train
20       55.719     57.403      A  0.895982          False       NaN             NaN       180.0          NaN        NaN              NaN     180.0   none
21       57.905     60.095      R  0.774234          False       NaN          59.355       315.0       59.356        NaN           59.721     315.0  train
22       60.597     63.788      R  1.257931           True     315.0          63.274       225.0       63.275     62.177           62.194     315.0  train
23       64.290     66.781      R  0.873128          False       NaN          66.092         0.0       66.093        NaN           66.443       0.0  train
24       67.283     69.289      R  0.601416           True     225.0          68.818       225.0       68.819     68.273           68.266     225.0  train
25       69.792     72.113      R  0.757687          False       NaN          71.246        90.0       71.247        NaN           71.549      90.0    val
26       72.616     73.283      A  0.961722           True       NaN             NaN       135.0          NaN        NaN              NaN       NaN   none
27       73.786     76.536      A  1.018893           True     315.0          75.932       270.0       75.933     74.552           74.571     315.0   none
28       77.039     79.763      I  0.698365          False       NaN          78.758       135.0       78.759        NaN           79.118     135.0   none
29       80.266     83.646      R  0.743176           True     135.0          83.036       135.0       83.037     82.325           82.333     135.0  train
30       84.148     87.331      R  1.371323          False       NaN          86.770       225.0       86.771        NaN           87.073     225.0  train
31       87.834     89.243      A  1.451542           True       NaN             NaN       270.0          NaN        NaN              NaN       NaN   none
32       89.745     91.708      A  0.874355           True     270.0             NaN        90.0          NaN     91.058              NaN     270.0   none
33       92.210     94.762      R  0.638304           True     225.0          94.221       270.0       94.222     93.218           93.211     225.0  train
34       95.264     98.013      R  0.738191           True     180.0          97.501       225.0       97.502     96.808           96.805     180.0    val
35       98.515    102.197      I  0.612102          False       NaN         101.192       270.0      101.193        NaN              NaN     270.0   none
36      102.699    104.769      A  1.081357           True       NaN             NaN       270.0          NaN        NaN              NaN       NaN   none
37      105.271    106.856      A  1.274152          False       NaN             NaN       135.0          NaN        NaN              NaN     135.0   none
38      107.358    113.557      I  1.419067          False       NaN         112.552        45.0      112.553        NaN          112.859      45.0   none
39      114.059    116.945      I  1.153755           True     135.0         115.940       225.0      115.941    115.308          115.320     135.0   none
40      117.447    120.567      R  0.725681           True     135.0         119.842        45.0      119.843    119.277          119.292     135.0    val
41      121.069    123.253      R  1.017380          False       NaN         122.616       270.0      122.617        NaN          122.917     270.0  train
42      123.755    124.984      A  0.735965           True       NaN             NaN       180.0          NaN        NaN              NaN       NaN   none
43      125.486    127.890      R  0.767937          False       NaN         126.920        90.0      126.921        NaN          127.265      90.0  train
44      128.392    130.850      A  1.169344           True       NaN             NaN       315.0          NaN        NaN              NaN       NaN   none
45      131.352    131.782      A  1.299627           True       NaN             NaN       225.0          NaN        NaN              NaN       NaN   none
46      132.284    135.062      R  0.678132           True     270.0         134.371        45.0      134.372    133.781          133.776     270.0    val
47      135.564    139.538      R  0.969065          False       NaN         138.716        45.0      138.717        NaN          138.991      45.0  train
48      140.040    140.342      A  1.088715           True       NaN             NaN        90.0          NaN        NaN              NaN       NaN   none
49      140.844    142.835      R  0.519004           True      45.0         142.305       225.0      142.306    141.835          141.828      45.0  train
50      143.338    146.913      R  1.386156           True     180.0         146.177        90.0      146.178    145.317          145.317     180.0  train
51      147.416    148.186      A  0.993039          False       NaN             NaN        90.0          NaN        NaN              NaN      90.0   none
52      148.688    150.741      R  0.616847          False       NaN         150.051        45.0      150.052        NaN          150.350      45.0  train
53      151.243    151.642      A  0.774519           True       NaN             NaN        90.0          NaN        NaN              NaN       NaN   none
54      152.144    155.065      R  1.337581           True     270.0         154.480        90.0      154.481    153.538          153.534     270.0  train
55      155.567    158.970      R  1.348927          False       NaN         158.243       225.0      158.244        NaN          158.541     225.0  train
56      159.473    161.751      R  0.999564          False       NaN         160.993       315.0      160.994        NaN          161.397     315.0  train
57      162.254    164.756      R  0.968536          False       NaN         163.931        45.0      163.932        NaN          164.247      45.0  train
58      165.258    167.688      R  0.871081           True     315.0         167.112       270.0      167.113    166.247          166.274     315.0    val
59      168.190    171.292      R  1.452790          False       NaN         170.577        45.0      170.578        NaN          170.838      45.0    val
60      171.794    172.274      A  0.647474          False       NaN             NaN         0.0          NaN        NaN              NaN       0.0   none
61      172.776    174.898      R  1.314664          False       NaN         174.276        90.0      174.277        NaN          174.591      90.0  train
62      175.400    179.407      R  1.249632          False       NaN         178.497        90.0      178.498        NaN          178.840      90.0  train
63      179.910    182.666      R  1.177758          False       NaN         182.047       225.0      182.048        NaN          182.320     225.0  train
64      183.169    184.283      A  1.477290           True       NaN             NaN         0.0          NaN        NaN              NaN       NaN   none
65      184.786    184.999      A  1.468813          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
66      185.501    186.155      A  1.351299          False       NaN             NaN       180.0          NaN        NaN              NaN     180.0   none
67      186.657    186.969      A  0.745828           True       NaN             NaN        90.0          NaN        NaN              NaN       NaN   none
68      187.471    190.597      R  1.162633           True      45.0         190.021       135.0      190.022    189.319          189.313      45.0    val
69      191.099    192.612      A  0.894515          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
70      193.114    195.771      R  1.364643          False       NaN         195.045         0.0      195.046        NaN          195.353       0.0  train
71      196.273    196.917      A  1.409297           True       NaN             NaN       315.0          NaN        NaN              NaN       NaN   none
72      197.419    199.248      R  0.666300          False       NaN         198.270       270.0      198.271        NaN          198.564     270.0  train
73      199.750    204.200      A  0.570291          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
74      204.702    206.273      A  0.978607          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
75      206.775    208.730      A  1.342607          False       NaN             NaN       315.0          NaN        NaN              NaN     315.0   none
76      209.232    210.799      A  1.341998          False       NaN             NaN       270.0          NaN        NaN              NaN     270.0   none
77      211.302    212.767      A  0.723702          False       NaN             NaN       180.0          NaN        NaN              NaN     180.0   none
78      213.269    213.910      A  1.264741          False       NaN             NaN       270.0          NaN        NaN              NaN     270.0   none
79      214.412    214.750      A  0.922576          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
80      215.252    220.196      A  0.666977          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
81      220.698    225.400      R  1.188717           True     225.0         224.852       225.0      224.853    224.221          224.213     225.0  train
82      225.902    228.276      A  1.414099           True     225.0             NaN        45.0          NaN    227.647              NaN     225.0   none
83      228.778    230.700      A  1.139484           True     270.0             NaN       180.0          NaN    230.191              NaN     270.0   none
84      231.202    239.763      R  1.284740          False       NaN         239.089         0.0      239.090        NaN          239.367       0.0    val
85      240.266    243.389      R  1.393749          False       NaN         242.599         0.0      242.600        NaN          242.946       0.0    val
86      243.892    246.798      R  1.311975          False       NaN         246.072         0.0      246.073        NaN          246.416       0.0    val
87      247.300    247.766      A  1.303725           True       NaN             NaN       135.0          NaN        NaN              NaN       NaN   none
88      248.269    248.634      A  1.275162          False       NaN             NaN         0.0          NaN        NaN              NaN       0.0   none
89      249.137    251.224      I  0.897845          False       NaN         250.219       270.0      250.220        NaN          250.528     270.0   none
90      251.726    254.362      R  0.798356          False       NaN         253.674       135.0      253.675        NaN          254.020     135.0  train
91      254.864    258.253      R  1.377235           True      90.0         257.675       135.0      257.676    257.109          257.105      90.0  train
92      258.756    262.703      R  0.988366           True     180.0         261.941         0.0      261.942    261.433          261.430     180.0  train
93      263.206    264.799      R  0.712772          False       NaN         264.102       315.0      264.103        NaN          264.409     315.0    val
94      265.301    268.188      R  1.309064          False       NaN         267.327       315.0      267.328        NaN          267.657     315.0  train
95      268.690    271.350      R  1.189510          False       NaN         270.647         0.0      270.648        NaN          270.967       0.0  train
96      271.852    273.576      I  0.535169          False       NaN         272.571         0.0      272.572        NaN          272.919       0.0   none
97      274.079    274.411      A  0.749878          False       NaN             NaN       315.0          NaN        NaN              NaN     315.0   none
98      274.913    278.142      I  0.604813           True      90.0         277.137        45.0      277.138    276.411          276.410      90.0   none
99      278.644    278.958      A  1.380912          False       NaN             NaN       315.0          NaN        NaN              NaN     315.0   none
100     279.460    283.631      I  0.539588           True     270.0         282.626       270.0      282.627    281.437          281.436     270.0   none
101     284.134    288.467      R  0.573953           True     135.0         287.604        90.0      287.605    287.193          287.209     135.0  train
102     288.970    289.392      A  1.299682          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
103     289.894    292.981      R  1.015539           True       0.0         292.121       270.0      292.122    291.030          291.025       0.0  train
104     293.483    296.891      R  1.294665           True     180.0         296.384       225.0      296.385    295.796          295.793     180.0  train
105     297.394    298.446      A  0.769349          False       NaN             NaN       135.0          NaN        NaN              NaN     135.0   none
106     298.949    302.973      R  1.104827           True       0.0         302.286        45.0      302.287    301.150          301.147       0.0  train
107     303.475    307.033      R  1.286472           True     270.0         306.247       180.0      306.248    305.262          305.254     270.0  train
108     307.535    310.626      R  0.505770           True      90.0         310.051       270.0      310.052    309.594          309.588      90.0    val
109     311.128    314.555      R  1.391453           True     225.0         313.831       315.0      313.832    312.837          312.829     225.0    val
110     315.058    315.641      A  1.298296          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
111     316.143    319.089      R  1.306473          False       NaN         318.171       315.0      318.172        NaN          318.552     315.0  train
112     319.591    322.701      R  1.311003          False       NaN         322.048         0.0      322.049        NaN          322.361       0.0  train
113     323.203    323.423      A  1.493045          False       NaN             NaN         0.0          NaN        NaN              NaN       0.0   none
114     323.926    325.559      R  0.785335          False       NaN         324.896       135.0      324.897        NaN          325.206     135.0  train
115     326.061    329.689      A  1.330405           True     270.0         329.066       180.0      329.067    328.323          328.320     270.0   none
116     330.191    331.117      A  0.999581          False       NaN             NaN       270.0          NaN        NaN              NaN     270.0   none
117     331.619    333.907      R  0.823603           True     315.0         333.086       315.0      333.087    332.530          332.546     315.0    val
118     334.410    336.428      R  0.727312          False       NaN         335.773         0.0      335.774        NaN          336.052       0.0  train
119     336.930    337.492      A  0.988654           True       NaN             NaN       180.0          NaN        NaN              NaN       NaN   none
120     337.995    339.967      R  1.035483          False       NaN         339.215       315.0      339.216        NaN          339.561     315.0  train
121     340.469    340.894      A  0.845990          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
122     341.396    344.627      I  1.070165           True       0.0         343.622       270.0      343.623    342.708          342.708       0.0   none
123     345.129    346.351      A  1.024888          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
124     346.854    349.531      A  1.475178           True      90.0             NaN       180.0          NaN    349.107              NaN      90.0   none
125     350.034    350.546      A  0.865571          False       NaN             NaN       135.0          NaN        NaN              NaN     135.0   none
126     351.048    354.858      R  1.033524          False       NaN         354.074       315.0      354.075        NaN          354.442     315.0  train
127     355.360    356.410      A  1.097352           True       NaN             NaN       180.0          NaN        NaN              NaN       NaN   none

In [46]:
for i in nwbfile.trials.to_dataframe()['split']:
    print(i)

test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test

In [85]:
trial_table = nwbfile.trials.to_dataframe()
print(trial_table.to_string())

     start_time  stop_time result  ctr_hold  ctr_hold_bump  bump_dir  target_on_time  target_dir  go_cue_time  bump_time  move_onset_time  cond_dir  split
id
0         0.502      4.556      R  1.106973          False       NaN           3.734        45.0        3.735        NaN            4.075      45.0    val
1         5.059      5.588      A  1.344188           True       NaN             NaN       225.0          NaN        NaN              NaN       NaN   none
2         6.090      9.374      I  1.170550           True     225.0           8.369       180.0        8.370      7.905            7.898     225.0   none
3         9.877     15.298      R  1.222202          False       NaN          14.318        45.0       14.319        NaN           14.656      45.0  train
4        15.800     17.005      A  0.777271          False       NaN             NaN       135.0          NaN        NaN              NaN     135.0   none
5        17.508     18.829      R  0.553678          False       NaN          18.245       270.0       18.246        NaN           18.508     270.0    val
6        19.331     22.551      R  1.424859          False       NaN          21.954       180.0       21.955        NaN           22.247     180.0  train
7        23.053     26.261      R  0.890691           True       0.0          25.656       135.0       25.657     25.062           25.062       0.0  train
8        26.764     28.601      A  0.573669           True       NaN             NaN       315.0          NaN        NaN              NaN       NaN   none
9        29.103     32.806      I  1.197885           True     135.0          31.801       225.0       31.802     31.265           31.280     135.0   none
10       33.308     35.997      R  0.590669           True     270.0          35.297         0.0       35.298     34.854           34.852     270.0    val
11       36.499     36.938      A  1.184729           True       NaN             NaN       270.0          NaN        NaN              NaN       NaN   none
12       37.440     37.687      A  1.431361           True       NaN          37.475        90.0          NaN        NaN              NaN       NaN   none
13       38.189     40.642      R  0.982830           True     135.0          39.847       315.0       39.848     39.357           39.371     135.0  train
14       41.144     42.004      A  1.045930           True       NaN             NaN       315.0          NaN        NaN              NaN       NaN   none
15       42.506     44.544      R  1.103750          False       NaN          43.795        45.0       43.796        NaN           44.107      45.0    val
16       45.046     45.451      A  1.260671          False       NaN             NaN         0.0          NaN        NaN              NaN       0.0   none
17       45.953     48.657      R  0.734950           True     225.0          47.935        45.0       47.936     46.764           46.757     225.0    val
18       49.159     51.658      R  1.095729          False       NaN          50.777       180.0       50.778        NaN           51.106     180.0  train
19       52.160     55.216      R  0.856059           True      90.0          54.580       180.0       54.581     54.094           54.088      90.0  train
20       55.719     57.403      A  0.895982          False       NaN             NaN       180.0          NaN        NaN              NaN     180.0   none
21       57.905     60.095      R  0.774234          False       NaN          59.355       315.0       59.356        NaN           59.721     315.0  train
22       60.597     63.788      R  1.257931           True     315.0          63.274       225.0       63.275     62.177           62.194     315.0  train
23       64.290     66.781      R  0.873128          False       NaN          66.092         0.0       66.093        NaN           66.443       0.0  train
24       67.283     69.289      R  0.601416           True     225.0          68.818       225.0       68.819     68.273           68.266     225.0  train
25       69.792     72.113      R  0.757687          False       NaN          71.246        90.0       71.247        NaN           71.549      90.0    val
26       72.616     73.283      A  0.961722           True       NaN             NaN       135.0          NaN        NaN              NaN       NaN   none
27       73.786     76.536      A  1.018893           True     315.0          75.932       270.0       75.933     74.552           74.571     315.0   none
28       77.039     79.763      I  0.698365          False       NaN          78.758       135.0       78.759        NaN           79.118     135.0   none
29       80.266     83.646      R  0.743176           True     135.0          83.036       135.0       83.037     82.325           82.333     135.0  train
30       84.148     87.331      R  1.371323          False       NaN          86.770       225.0       86.771        NaN           87.073     225.0  train
31       87.834     89.243      A  1.451542           True       NaN             NaN       270.0          NaN        NaN              NaN       NaN   none
32       89.745     91.708      A  0.874355           True     270.0             NaN        90.0          NaN     91.058              NaN     270.0   none
33       92.210     94.762      R  0.638304           True     225.0          94.221       270.0       94.222     93.218           93.211     225.0  train
34       95.264     98.013      R  0.738191           True     180.0          97.501       225.0       97.502     96.808           96.805     180.0    val
35       98.515    102.197      I  0.612102          False       NaN         101.192       270.0      101.193        NaN              NaN     270.0   none
36      102.699    104.769      A  1.081357           True       NaN             NaN       270.0          NaN        NaN              NaN       NaN   none
37      105.271    106.856      A  1.274152          False       NaN             NaN       135.0          NaN        NaN              NaN     135.0   none
38      107.358    113.557      I  1.419067          False       NaN         112.552        45.0      112.553        NaN          112.859      45.0   none
39      114.059    116.945      I  1.153755           True     135.0         115.940       225.0      115.941    115.308          115.320     135.0   none
40      117.447    120.567      R  0.725681           True     135.0         119.842        45.0      119.843    119.277          119.292     135.0    val
41      121.069    123.253      R  1.017380          False       NaN         122.616       270.0      122.617        NaN          122.917     270.0  train
42      123.755    124.984      A  0.735965           True       NaN             NaN       180.0          NaN        NaN              NaN       NaN   none
43      125.486    127.890      R  0.767937          False       NaN         126.920        90.0      126.921        NaN          127.265      90.0  train
44      128.392    130.850      A  1.169344           True       NaN             NaN       315.0          NaN        NaN              NaN       NaN   none
45      131.352    131.782      A  1.299627           True       NaN             NaN       225.0          NaN        NaN              NaN       NaN   none
46      132.284    135.062      R  0.678132           True     270.0         134.371        45.0      134.372    133.781          133.776     270.0    val
47      135.564    139.538      R  0.969065          False       NaN         138.716        45.0      138.717        NaN          138.991      45.0  train
48      140.040    140.342      A  1.088715           True       NaN             NaN        90.0          NaN        NaN              NaN       NaN   none
49      140.844    142.835      R  0.519004           True      45.0         142.305       225.0      142.306    141.835          141.828      45.0  train
50      143.338    146.913      R  1.386156           True     180.0         146.177        90.0      146.178    145.317          145.317     180.0  train
51      147.416    148.186      A  0.993039          False       NaN             NaN        90.0          NaN        NaN              NaN      90.0   none
52      148.688    150.741      R  0.616847          False       NaN         150.051        45.0      150.052        NaN          150.350      45.0  train
53      151.243    151.642      A  0.774519           True       NaN             NaN        90.0          NaN        NaN              NaN       NaN   none
54      152.144    155.065      R  1.337581           True     270.0         154.480        90.0      154.481    153.538          153.534     270.0  train
55      155.567    158.970      R  1.348927          False       NaN         158.243       225.0      158.244        NaN          158.541     225.0  train
56      159.473    161.751      R  0.999564          False       NaN         160.993       315.0      160.994        NaN          161.397     315.0  train
57      162.254    164.756      R  0.968536          False       NaN         163.931        45.0      163.932        NaN          164.247      45.0  train
58      165.258    167.688      R  0.871081           True     315.0         167.112       270.0      167.113    166.247          166.274     315.0    val
59      168.190    171.292      R  1.452790          False       NaN         170.577        45.0      170.578        NaN          170.838      45.0    val
60      171.794    172.274      A  0.647474          False       NaN             NaN         0.0          NaN        NaN              NaN       0.0   none
61      172.776    174.898      R  1.314664          False       NaN         174.276        90.0      174.277        NaN          174.591      90.0  train
62      175.400    179.407      R  1.249632          False       NaN         178.497        90.0      178.498        NaN          178.840      90.0  train
63      179.910    182.666      R  1.177758          False       NaN         182.047       225.0      182.048        NaN          182.320     225.0  train
64      183.169    184.283      A  1.477290           True       NaN             NaN         0.0          NaN        NaN              NaN       NaN   none
65      184.786    184.999      A  1.468813          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
66      185.501    186.155      A  1.351299          False       NaN             NaN       180.0          NaN        NaN              NaN     180.0   none
67      186.657    186.969      A  0.745828           True       NaN             NaN        90.0          NaN        NaN              NaN       NaN   none
68      187.471    190.597      R  1.162633           True      45.0         190.021       135.0      190.022    189.319          189.313      45.0    val
69      191.099    192.612      A  0.894515          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
70      193.114    195.771      R  1.364643          False       NaN         195.045         0.0      195.046        NaN          195.353       0.0  train
71      196.273    196.917      A  1.409297           True       NaN             NaN       315.0          NaN        NaN              NaN       NaN   none
72      197.419    199.248      R  0.666300          False       NaN         198.270       270.0      198.271        NaN          198.564     270.0  train
73      199.750    204.200      A  0.570291          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
74      204.702    206.273      A  0.978607          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
75      206.775    208.730      A  1.342607          False       NaN             NaN       315.0          NaN        NaN              NaN     315.0   none
76      209.232    210.799      A  1.341998          False       NaN             NaN       270.0          NaN        NaN              NaN     270.0   none
77      211.302    212.767      A  0.723702          False       NaN             NaN       180.0          NaN        NaN              NaN     180.0   none
78      213.269    213.910      A  1.264741          False       NaN             NaN       270.0          NaN        NaN              NaN     270.0   none
79      214.412    214.750      A  0.922576          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
80      215.252    220.196      A  0.666977          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
81      220.698    225.400      R  1.188717           True     225.0         224.852       225.0      224.853    224.221          224.213     225.0  train
82      225.902    228.276      A  1.414099           True     225.0             NaN        45.0          NaN    227.647              NaN     225.0   none
83      228.778    230.700      A  1.139484           True     270.0             NaN       180.0          NaN    230.191              NaN     270.0   none
84      231.202    239.763      R  1.284740          False       NaN         239.089         0.0      239.090        NaN          239.367       0.0    val
85      240.266    243.389      R  1.393749          False       NaN         242.599         0.0      242.600        NaN          242.946       0.0    val
86      243.892    246.798      R  1.311975          False       NaN         246.072         0.0      246.073        NaN          246.416       0.0    val
87      247.300    247.766      A  1.303725           True       NaN             NaN       135.0          NaN        NaN              NaN       NaN   none
88      248.269    248.634      A  1.275162          False       NaN             NaN         0.0          NaN        NaN              NaN       0.0   none
89      249.137    251.224      I  0.897845          False       NaN         250.219       270.0      250.220        NaN          250.528     270.0   none
90      251.726    254.362      R  0.798356          False       NaN         253.674       135.0      253.675        NaN          254.020     135.0  train
91      254.864    258.253      R  1.377235           True      90.0         257.675       135.0      257.676    257.109          257.105      90.0  train
92      258.756    262.703      R  0.988366           True     180.0         261.941         0.0      261.942    261.433          261.430     180.0  train
93      263.206    264.799      R  0.712772          False       NaN         264.102       315.0      264.103        NaN          264.409     315.0    val
94      265.301    268.188      R  1.309064          False       NaN         267.327       315.0      267.328        NaN          267.657     315.0  train
95      268.690    271.350      R  1.189510          False       NaN         270.647         0.0      270.648        NaN          270.967       0.0  train
96      271.852    273.576      I  0.535169          False       NaN         272.571         0.0      272.572        NaN          272.919       0.0   none
97      274.079    274.411      A  0.749878          False       NaN             NaN       315.0          NaN        NaN              NaN     315.0   none
98      274.913    278.142      I  0.604813           True      90.0         277.137        45.0      277.138    276.411          276.410      90.0   none
99      278.644    278.958      A  1.380912          False       NaN             NaN       315.0          NaN        NaN              NaN     315.0   none
100     279.460    283.631      I  0.539588           True     270.0         282.626       270.0      282.627    281.437          281.436     270.0   none
101     284.134    288.467      R  0.573953           True     135.0         287.604        90.0      287.605    287.193          287.209     135.0  train
102     288.970    289.392      A  1.299682          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
103     289.894    292.981      R  1.015539           True       0.0         292.121       270.0      292.122    291.030          291.025       0.0  train
104     293.483    296.891      R  1.294665           True     180.0         296.384       225.0      296.385    295.796          295.793     180.0  train
105     297.394    298.446      A  0.769349          False       NaN             NaN       135.0          NaN        NaN              NaN     135.0   none
106     298.949    302.973      R  1.104827           True       0.0         302.286        45.0      302.287    301.150          301.147       0.0  train
107     303.475    307.033      R  1.286472           True     270.0         306.247       180.0      306.248    305.262          305.254     270.0  train
108     307.535    310.626      R  0.505770           True      90.0         310.051       270.0      310.052    309.594          309.588      90.0    val
109     311.128    314.555      R  1.391453           True     225.0         313.831       315.0      313.832    312.837          312.829     225.0    val
110     315.058    315.641      A  1.298296          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
111     316.143    319.089      R  1.306473          False       NaN         318.171       315.0      318.172        NaN          318.552     315.0  train
112     319.591    322.701      R  1.311003          False       NaN         322.048         0.0      322.049        NaN          322.361       0.0  train
113     323.203    323.423      A  1.493045          False       NaN             NaN         0.0          NaN        NaN              NaN       0.0   none
114     323.926    325.559      R  0.785335          False       NaN         324.896       135.0      324.897        NaN          325.206     135.0  train
115     326.061    329.689      A  1.330405           True     270.0         329.066       180.0      329.067    328.323          328.320     270.0   none
116     330.191    331.117      A  0.999581          False       NaN             NaN       270.0          NaN        NaN              NaN     270.0   none
117     331.619    333.907      R  0.823603           True     315.0         333.086       315.0      333.087    332.530          332.546     315.0    val
118     334.410    336.428      R  0.727312          False       NaN         335.773         0.0      335.774        NaN          336.052       0.0  train
119     336.930    337.492      A  0.988654           True       NaN             NaN       180.0          NaN        NaN              NaN       NaN   none
120     337.995    339.967      R  1.035483          False       NaN         339.215       315.0      339.216        NaN          339.561     315.0  train
121     340.469    340.894      A  0.845990          False       NaN             NaN        45.0          NaN        NaN              NaN      45.0   none
122     341.396    344.627      I  1.070165           True       0.0         343.622       270.0      343.623    342.708          342.708       0.0   none
123     345.129    346.351      A  1.024888          False       NaN             NaN       225.0          NaN        NaN              NaN     225.0   none
124     346.854    349.531      A  1.475178           True      90.0             NaN       180.0          NaN    349.107              NaN      90.0   none
125     350.034    350.546      A  0.865571          False       NaN             NaN       135.0          NaN        NaN              NaN     135.0   none
126     351.048    354.858      R  1.033524          False       NaN         354.074       315.0      354.075        NaN          354.442     315.0  train
127     355.360    356.410      A  1.097352           True       NaN             NaN       180.0          NaN        NaN              NaN       NaN   none